// <auto-generated />
using AlternetSiparisYazilimi.Models.VeritabaniSebatKatmani;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AlternetSiparisYazilimi.Migrations
{
    [DbContext(typeof(AlternetSiparisDbContext))]
    [Migration("20190127150421_ilkGoc")]
    partial class ilkGoc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlternetSiparisYazilimi.Models.Urun", b =>
                {
                    b.Property<int>("UrunID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aciklama");

                    b.Property<decimal>("Fiyat");

                    b.Property<string>("Isim");

                    b.Property<string>("Kategorisi");

                    b.Property<byte[]>("UrunResmi");

                    b.HasKey("UrunID");

                    b.ToTable("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
